# Generated by Django 4.0.6 on 2022-08-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('fecha_nac', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('fecha_nac', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='nombre',
        ),
    ]
